region = "ap-south-1"
domain = "rahilresume.com"
static_site_path = "/home/rahil/CloudResumeChallenge/personal-site/build"
dynamodb_item_name = "view_count"
dynamodb_table_name = "Site-Stats"
resource_name_api = "stats"
