name: CI Workflow

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:

  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'ap-south-1'
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform  

      # Check if the resource is already in the Terraform state
      - name: Check if Route 53 zone is already imported
        id: check_import
        run: |
          if terraform state list | grep -q 'module.route53.aws_route53_zone.site_host_zone'; then
            echo "Resource already imported"
            echo "import=false" >> $GITHUB_ENV
          else
            echo "Resource not imported yet"
            echo "import=true" >> $GITHUB_ENV
          fi

      # Import the Route 53 zone if it is not already in the state
      - name: Terraform Import
        if: env.import == 'true'
        run: terraform import module.route53.aws_route53_zone.site_host_zone Z025011125N7CMVFB4813
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform  

  test:
    needs: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      # Install dependencies for Playwright (skip browsers)
      - name: Install dependencies
        run: npm ci
        working-directory: ./playwright 

      - name: Install WebKit browser
        run: npx playwright install webkit
        working-directory: ./playwright 

      - name: Run Playwright tests
        run: npx playwright test e2e.spec.js
        working-directory: ./playwright 

      # Upload Playwright test results
      - name: Upload Playwright test results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: ./playwright/playwright-report/
          retention-days: 30